server:
  port: 8001
spring:
  cloud:
    config:
      server:
        git:
          default-label: eureka
          uri: https://github.com/AlPetrovich/Microservices-Backend
          search-paths: config-data
  application:
    name: config-service

